---
name: Pandoctor
description: Converts .md files into .html

inputs:
  ignore:
    description: Specify files to not convert
    required: true
    default: README.md
  template:
    description: Specify pandoc html template file
    required: true
    default: ${{ github.action_path }}/dummy.html
runs:
  using: "composite"
  steps:
    - name: Set up pandoc
      uses: nikeee/setup-pandoc@v1
    - name: Convert markdown into html
      shell: bash
      env:
        IGNORE: ${{ inputs.ignore }}
        TEMPLATE: ${{ inputs.template }}
      run: make -f "${{ github.action_path }}/Makefile" all purge-deploy
