---
name: Pandoctor
description: Converts .md files into .html

inputs:
  ignore:
    description: Specify files to not convert
    required: false
  template:
    description: Specify pandoc html template file
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up pandoc
      uses: nikeee/setup-pandoc@v1
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Convert markdown into html
      shell: bash
      env:
        IGNORE: ${{ inputs.ignore }}
        TEMPLATE: ${{ inputs.template }}
      run: make all purge-deploy
